### ISSUE TITLE
Normalizer Not working with other Options

### ISSUE THREAD

**Issue by bsaid5654** [anoopkunchukuttan/indic_nlp_library#21]
This is the error it is throwing when I try any other option other than "do_nothing"  can you please check why this is happening
Traceback (most recent call last):
  File "indic_nlp_library/src/indicnlp/normalize/indic_normalize.py", line 720, in <module>
    normalizer=factory.get_normalizer(language,remove_nuktas,normalize_nasals)
  File "indic_nlp_library/src/indicnlp/normalize/indic_normalize.py", line 680, in get_normalizer
    normalizer=TeluguNormalizer(lang=language, remove_nuktas=remove_nuktas, nasals_mode=nasals_mode)
  File "indic_nlp_library/src/indicnlp/normalize/indic_normalize.py", line 542, in __init__
    super(TeluguNormalizer,self).__init__(lang,remove_nuktas,nasals_mode)
  File "indic_nlp_library/src/indicnlp/normalize/indic_normalize.py", line 69, in __init__
    self._init_normalize_nasals()
  File "indic_nlp_library/src/indicnlp/normalize/indic_normalize.py", line 183, in _init_normalize_nasals
    self._init_to_anusvaara_strict()
  File "indic_nlp_library/src/indicnlp/normalize/indic_normalize.py", line 93, in _init_to_anusvaara_strict
    nasal=langinfo.offset_to_char(pat_signature[0],self.lang),
  File "indic_nlp_library/src/indicnlp/langinfo.py", line 91, in offset_to_char
    return chr(c+SCRIPT_RANGES[lang][0])
ValueError: chr() arg not in range(256)

**Comment by anoopkunchukuttan** [comment]
Can you share the call and arguments?

**Comment by anoopkunchukuttan** [comment]
Not reproducible, most likely an issue of wrong file encoding or using Python2.
