### ISSUE TITLE
installation of latest version not working correctly

### ISSUE THREAD

**Issue by m-sean** [anoopkunchukuttan/indic_nlp_library#47]
Hi, I've been working with your library and noticed today that the latest version (0.80) is not installing properly:
```
>>> import indicnlp
Traceback (most recent call last):
  File "/Users/seanmiller/pyenv/lib/python3.8/site-packages/indicnlp/__init__.py", line 5, in <module>
    from .version import __version__  # noqa
ModuleNotFoundError: No module named 'indicnlp.version'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/seanmiller/pyenv/lib/python3.8/site-packages/indicnlp/__init__.py", line 8, in <module>
    with open(version_txt) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/seanmiller/pyenv/lib/python3.8/site-packages/indicnlp/version.txt'
```

I didn't get this error with the previous version (0.71).

**Comment by m-sean** [comment]
Sorry—for clarity, I'm specifically referring to the PyPi release. I just checked and installing from source works fine.

**Comment by m-sean** [comment]
thanks for fixing it so quickly! it's working now. 
heads up, the comment on line #10 of  `setup.py` should probably be updated
