### ISSUE TITLE
Issue with Urdu word segmenter

### ISSUE THREAD

**Issue by patelrajnath** [anoopkunchukuttan/indic_nlp_library#6]
Hi, 
I am trying to use word segmentation for Urdu, but getting following error-
-----------------
Traceback (most recent call last):
  File "/home/raj/smt/decoder/indic_nlp_library/src/indicnlp/morph/unsupervised_morph.py", line 136, in <module>
    analyzer=UnsupervisedMorphAnalyzer(language,add_marker)
  File "/home/raj/smt/decoder/indic_nlp_library/src/indicnlp/morph/unsupervised_morph.py", line 53, in __init__
    self._script_range_pat=ur'^[{}-{}]+$'.format(unichr(langinfo.SCRIPT_RANGES[lang][0]),unichr(langinfo.SCRIPT_RANGES[lang][1]))
KeyError: 'ur'
---------------
Kindly check for the same. 
Thank you.

**Comment by anoopkunchukuttan** [comment]
Urdu is now supported
